### ISSUE TITLE
Enable triagebot

### ISSUE THREAD

**Issue by camelid** [rust-lang/reference#859]
Mainly to enable assignment and labeling by non-members.

I suggest something like:

```toml
[relabel]
allow-unauthenticated = [
    "A-*", "New Content", "Language Cleanup", "Easy", "Formatting", "Enhancement", "Bug",
]

[assign]
```

Cc rust-lang/www.rust-lang.org#1179
